name: Update Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/generate_sitemap.py'
      - 'docs/data/projects.json'  # Update sitemap when content changes
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 12 * * 1'  # Run weekly on Mondays at noon UTC

concurrency:
  group: sitemap-update
  cancel-in-progress: true

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging sitemap generation
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install python-dateutil
    
    - name: Generate sitemap
      run: |
        python scripts/generate_sitemap.py
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code docs/sitemap.xml || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/sitemap.xml
        git commit -m "Auto-update sitemap.xml"
        git push